name: hippopants
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_easyloading: ^3.0.5
  google_fonts: ^6.2.1
  intl: ^0.19.0
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1


flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png
  android: true
  ios: true
  android_12:
    color: "#FFFFFF"
  ios_content_mode: center
  android_gravity: center

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.png"
  remove_alpha_ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/banner/
    - assets/images/category/
    - assets/images/promotion/
    - assets/images/product/